name: 'Deploy'

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ants
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: List workspaces to lint
        id: lint
        run: echo "::set-output name=matrix::$(yarn jill list --with-script lint --json)"

      - name: List workspaces to test
        id: test
        run: echo "::set-output name=matrix::$(yarn jill list --with-script test --json)"

    outputs:
      matrix-lint: ${{ steps.lint.outputs.matrix }}
      matrix-test: ${{ steps.test.outputs.matrix }}

  build-libs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build libraries
        run: yarn run build:libs

      - uses: actions/upload-artifact@v3
        with:
          name: build-libs-artifacts
          path: libs/*/dist/*

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{ fromJson(needs.setup.outputs.matrix-lint)[0] }}

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix-lint) }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn workspace ${{ matrix.name }} lint

  test:
    runs-on: ubuntu-latest
    needs: [setup, build-libs]
    if: ${{ fromJson(needs.setup.outputs.matrix-lint)[0] }}

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix-test) }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v3
        with:
          name: build-libs-artifacts
          path: libs

      - name: Test
        run: yarn workspace ${{ matrix.name }} test

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.slug }}-coverage
          path: ${{ matrix.root }}/coverage

  terraform:
    runs-on: ubuntu-latest
    needs: [lint, test]

    environment: terraform

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -input=false

  deploy-api:
    name: 'deploy @ants/api'
    runs-on: ubuntu-latest
    needs: [ terraform ]

    environment:
      name: serverless
      url: ${{ steps.info.outputs.api_url }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v3
        with:
          name: build-libs-artifacts
          path: libs

      - name: Deploy api
        run: yarn workspace @ants/api sls deploy --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Get outputs
        id: output
        run: |
          echo "::set-output name=HttpApiUrl::$(yarn workspace @ants/api sls info --verbose | grep HttpApiUrl | cut -d' ' -f 4)"
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    outputs:
      HttpApiUrl: ${{ steps.output.outputs.HttpApiUrl }}

  deploy-ants:
    name: 'deploy @ants/frontend'
    runs-on: ubuntu-latest
    needs: [ deploy-api ]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: yarn

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-3
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v3
        with:
          name: build-libs-artifacts
          path: libs

      - name: Build frontend
        run: yarn workspace @ants/frontend build
        env:
          API_URL: ${{ needs.deploy-api.outputs.HttpApiUrl }}

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'apps/frontend/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
